### ISSUE TITLE
感谢开源你的劳动成果

### ISSUE THREAD

**Issue by geekyes** [fa1247/PYCAN#1]
特用 Issues 来表达感谢，谢谢大大开源。
另外一个想说明下的就是，大大的文件没有协议控制，我也没有 fork ，是直接 clone 后拷贝需要的文件。但是我在我的工程里面有说明文件来源，如下图：
![image](https://user-images.githubusercontent.com/31738262/46794578-b9b2b100-cd7a-11e8-8586-6c2b15f1c6c5.png)

特使用 Issues 来告知大大。
最后，再次感谢！

**Comment by fa1247** [comment]
目前还很不完善，只支持少数CAN卡和少量函数，作为自己用的简陋上位机而开发，欢迎Pull request. : )

**Comment by geekyes** [comment]
要的，特别荣幸
