### ISSUE TITLE
请问测试过数据发送吗？

### ISSUE THREAD

**Issue by 123zmz123** [fa1247/PYCAN#2]
我根据自己和网上查找的代码，能够用python 控制ＵＳＢ_CAN_2EU ，接收数据解析数据都没问题，但是发送数据时，似乎只能传递帧ID， 作为结构体中的Data数组似乎无法顺利通过python传递给dll所定义的函数中请问这个该如何做解？

**Comment by 123zmz123** [comment]
已经解决，
我不知道作者是如何写的，但是我最终传入数据的时候是这样写的，
a = VCI_CAN_OBJ()
a.Data = (c_ubyte*8)(data[0],data[1],data[2],data[3],data[4],data[5],data[6],data[7])
这样能够正常发送数据了

**Comment by fa1247** [comment]
> 已经解决，
> 我不知道作者是如何写的，但是我最终传入数据的时候是这样写的，
> a = VCI_CAN_OBJ()
> a.Data = (c_ubyte*8)(data[0],data[1],data[2],data[3],data[4],data[5],data[6],data[7])
> 这样能够正常发送数据了

刚刚为VCI_CAN_OBJ()类增加了getdata与setdata方法
使用VCI_CAN_OBJ().getdata()可获取list格式数据
```
>>>frame.getdata()
[255, 255, 0, 0]
```
使用VCI_CAN_OBJ().setdata()可将list格式数据赋给实例，list长度自动成为DataLen
并未对传入参数做判断，请谨慎传参
```
>>>frame = VCI_CAN_OBJ()
>>>datalist = [0,1,2,3,255,255]
>>>frame.setdata(datalist)
>>>frame.getdata()
[0, 1, 2, 3, 255, 255]
>>>frame.DataLen
6
```
